# Generated by Django 4.2.3 on 2023-07-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_enquiry_enquirie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('profit1', models.IntegerField()),
                ('profit2', models.IntegerField()),
                ('profit3', models.IntegerField()),
                ('profit4', models.IntegerField()),
            ],
        ),
    ]
