# Generated by Django 4.2.3 on 2023-07-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_number_balance_alter_number_profit1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='profit5',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
