# Generated by Django 4.2.3 on 2023-07-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_number_balance_alter_number_profit1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(blank=True, max_length=100)),
                ('profit', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
