# Generated by Django 4.2.3 on 2023-07-31 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_extraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extraction',
        ),
    ]
